apiVersion: v2
name: tk-doc
description: A Helm chart for TK Doc - a modern Next.js documentation platform
keywords:
  - documentation
  - nextjs
  - tk-doc
home: https://doc.tkweb.dev
sources:
  - https://github.com/dedkola/tk-doc
maintainers:
  - name: dedkola
    url: https://github.com/dedkola
type: application
version: 0.1.0
appVersion: "0.1.0"
