apiVersion: v1
kind: Service
metadata:
  name: {{ include "tk-doc.fullname" . }}-service
  labels:
    {{- include "tk-doc.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "tk-doc.selectorLabels" . | nindent 4 }}
